server.port: 8085

# Spring Config
spring:
  application:
    name: visit-service
  cloud:
    refresh:
      refreshable: false
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
    username: root
    password: petclinic
    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none

kafka:
  bootstrap:
    config:
      server: localhost:9092

# Logging
logging.level.org.springframework: INFO

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
