server.port: 8083

# Logging
logging.level.org.springframework: INFO

# Spring Config
spring:
  application:
    name: owners-service
  cloud:
    refresh:
      refreshable: false

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

customers-service:
  url: "http://localhost:8080"
  ribbon:
    eureka:
      enabled: false
visits-service:
  url: "http://localhost:8085"
  ribbon:
    eureka:
      enabled: false
